site_name: Echemos un bitstazo
theme:
  name: readthedocs
  analytics:
    gtag: UA-114291557-1
  highlightjs: true
  hljs_languages:
      - yaml
      - bash
      - python
  locale: es
  collapse_navigation: False
  navigation_depth: 1
